.github/workflows/ci.yaml
.gitignore
.go-header.yaml
.golangci.yml
.license/README.md
.license/template.txt
.yamllint.yml
staticcheck.conf

Add initial CI for cmd-registry-memory

---

.github/workflows/pr-for-updates.yaml

Add ci action for pr updates

---

main.go

Add a possible to configure ExpirePeriod via config

---

.github/workflows/ci.yaml

This PR adds possibility to publish docker images into repo registry

Add image publishing for cmd-registry-memory

---

.github/workflows/ci.yaml

Run publishing image job on merge

---

go.mod
go.sum
main.go

Update cmd-registry-memory to latest SDK

---

.github/workflows/docker-push.yaml

Pr fixes problem:  https://github.com/networkservicemesh/cmd-registry-memory/actions?query=workflow%3A.github%2Fworkflows%2Fdocker-push.yaml

Add missed run directive for image publishing job

---

.github/workflows/docker-push.yaml

Fix names and add target runtime for docker push job

---

go.mod
go.sum
main.go

Update sdk dependency to latest and fix compilation errors

---

.github/workflows/docker-push.yaml
main.go
main_test.go
pkg/imports/imports.go

Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>

Update registry-memory config

---

main.go

Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>

fix: registry-memory: connect chain element should use spire tlsconfig

---

.templateignore
exclude.patch.conf
go.mod

Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>

Adapt to latest cmd-template

---

main.go

Added jaeger initialization and tracing grpc options

Adapt cmd-registry-memory to use opentracing

---

.github/workflows/automerge.yaml
.github/workflows/ci.yaml
.github/workflows/docker-push.yaml
.github/workflows/update-deployments.yaml
go.mod
go.sum

Closes https://github.com/networkservicemesh/cmd-registry-memory/pull/258
networkservicemesh/sdk#819

fix issue related to sync with latest cmd-template 

---

go.mod
go.sum
main_test.go
pkg/imports/gen.go
pkg/imports/imports_linux.go

Signed-off-by: Vladimir Popov <vladimir.popov@xored.com>

Update to the latest sdk version

---

Dockerfile
main.go
pkg/imports/imports_linux.go

Signed-off-by: Mikhail <avramenkomihail15@gmail.com>
https://github.com/networkservicemesh/sdk/issues/759

removed signalctx, added NotifyContext

---

Dockerfile

Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
Closes https://github.com/networkservicemesh/cmd-registry-memory/issues/240

feat: Add grpc health probe

---

go.mod
go.sum
main_test.go
pkg/imports/imports_linux.go

Closes https://github.com/networkservicemesh/cmd-registry-memory/pull/316

Manually update to the latest sdk version

---

Dockerfile
go.mod
main.go
main_test.go
pkg/imports/imports_linux.go

Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
Related to https://github.com/networkservicemesh/deployments-k8s/pull/1783

fix: registry-memory doesn't work in interdomain scenarios.

---

go.mod
go.sum
main_test.go
pkg/imports/imports_linux.go

Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>

Update to the lastest sdk manually

---

Dockerfile

https://github.com/networkservicemesh/deployments-k8s/issues/11427

Update gRPC health probe to fix CVEs
